import ExcelJS from "exceljs";
import { styleHeaderRow, setupPrint, autofitColumns } from "./styling";
import type { CongregationReportData } from "../data";
import type { Category } from "@/lib/domain/categories";

const CATEGORY_LABEL: Record<Category, string> = { publisher: "Publishers", auxiliary_pioneer: "Auxiliary pioneers", regular_pioneer: "Regular pioneers", special_pioneer: "Special pioneers" };

/** EXP-01 Excel: Summary, Detail, Not reported, By group, About (§12.2). Totals are live formulas so figures
 * recalculate if someone corrects a cell, as the spec asks. */
export async function buildCongregationExcel(data: CongregationReportData, opts: { lang: "en" | "sw"; includeComments: boolean; generatedBy: string }): Promise<Buffer> {
  const { month, rows, summary, groups, letterhead } = data;
  const wb = new ExcelJS.Workbook();
  wb.creator = "Ministry Report";
  wb.title = `Congregation Ministry Report — ${month}`;

  // --- Summary ---
  const sum = wb.addWorksheet("Summary");
  sum.addRow(["Category", "Reporting", "Hours", "Studies"]);
  styleHeaderRow(sum.getRow(1));
  const cats: Category[] = ["publisher", "auxiliary_pioneer", "regular_pioneer", "special_pioneer"];
  cats.forEach((c) => sum.addRow([CATEGORY_LABEL[c], summary.byCategory[c].reporting, c === "publisher" ? null : summary.byCategory[c].hours, summary.byCategory[c].studies]));
  const firstDataRow = 2, lastDataRow = 1 + cats.length;
  sum.addRow(["Congregation total", { formula: `SUM(B${firstDataRow}:B${lastDataRow})` }, { formula: `SUM(C${firstDataRow}:C${lastDataRow})` }, { formula: `SUM(D${firstDataRow}:D${lastDataRow})` }]);
  sum.getRow(lastDataRow + 1).font = { bold: true };
  autofitColumns(sum, [22, 12, 10, 10]);
  setupPrint(sum);
  sum.views = [{ state: "frozen", ySplit: 1 }];

  // --- By group ---
  const byGroupWs = wb.addWorksheet("By group");
  byGroupWs.addRow(["Group", "Reported", "Obligated", "Hours", "Studies"]);
  styleHeaderRow(byGroupWs.getRow(1));
  groups.forEach((g) => byGroupWs.addRow([g.group_name, g.reported, g.obligated, g.hours, g.studies]));
  autofitColumns(byGroupWs, [22, 12, 12, 10, 10]);
  setupPrint(byGroupWs);
  byGroupWs.views = [{ state: "frozen", ySplit: 1 }];

  // --- Detail ---
  const detail = wb.addWorksheet("Detail");
  const header = ["Name", "Group", "Category", "Status", "Participated", "Hours", "Studies", "On time / Late"];
  if (opts.includeComments) header.push("Comment");
  detail.addRow(header);
  styleHeaderRow(detail.getRow(1));
  for (const r of rows) {
    const row = [
      r.full_name, r.group_name ?? "—", r.category ? CATEGORY_LABEL[r.category] : "—",
      r.status === "missing" ? "Not yet" : r.status === "not_reported" ? "Did not report" : "Submitted",
      r.category === "publisher" ? (r.participated ? "Yes" : "No") : "—",
      r.category && r.category !== "publisher" ? r.hours : null, r.studies ?? null,
      r.status === "missing" || r.status === "not_reported" ? "—" : r.is_late ? "Late" : "On time",
    ];
    if (opts.includeComments) row.push(r.comment ?? "");
    detail.addRow(row);
  }
  detail.autoFilter = { from: "A1", to: `${opts.includeComments ? "I" : "H"}1` };
  detail.views = [{ state: "frozen", xSplit: 1, ySplit: 1 }];
  autofitColumns(detail, opts.includeComments ? [22, 14, 18, 14, 12, 8, 8, 12, 30] : [22, 14, 18, 14, 12, 8, 8, 12]);
  setupPrint(detail);

  // --- Not reported ---
  const nr = wb.addWorksheet("Not reported");
  nr.addRow(["Name", "Group"]);
  styleHeaderRow(nr.getRow(1));
  rows.filter((r) => r.status === "missing").forEach((r) => nr.addRow([r.full_name, r.group_name ?? "—"]));
  autofitColumns(nr, [26, 18]);
  setupPrint(nr);

  // --- About ---
  const about = wb.addWorksheet("About");
  about.addRow(["Month", month]);
  about.addRow(["Language", opts.lang]);
  about.addRow(["Comments included", opts.includeComments ? "Yes" : "No"]);
  about.addRow(["Generated by", opts.generatedBy]);
  about.addRow(["Congregation", letterhead.congregationName]);
  about.addRow(["Generated at", new Date().toISOString()]);
  autofitColumns(about, [20, 40]);

  return Buffer.from(await wb.xlsx.writeBuffer());
}
